version: "3"
services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "9000:8081"
    volumes:
      - ./data:/nexus-data    // Cambie el ./data aquí por la ruta de la carpeta que creó usted mismo
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
    restart: always
