version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    container_name: gitlab-runner 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_BASE}/gitlab_runner_config:/etc/gitlab-runner
    restart: unless-stopped

