version: '3'

services:
  nexus:
    image: sonatype/nexus3:${NEXUS_VERSION}
    container_name: nexus3
    volumes:
      - ${VOLUME_BASE}/nexus:/nexus-data
    ports:
      - "8081:8081"
      - "6000:6000"
      - "6001:6001"
    restart: unless-stopped


