version: '3'

services:
  sonarqube:
    image: sonarqube:${SONAQUBE_VERSION}
    container_name: sonarqube
    #platform: linux/x86_64
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    # networks:
    #   - sonarnet
    environment:
      SONAR_JDBC_URL: ${SONAR_DB_URL}
      SONAR_JDBC_USERNAME: ${SONAR_DB_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_PASS}
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
    volumes:
      - ${VOLUME_BASE}/sonarqube_data:/opt/sonarqube/data
      - ${VOLUME_BASE}/sonarqube_extensions:/opt/sonarqube/extensions
      - ${VOLUME_BASE}/sonarqube_logs:/opt/sonarqube/logs
      - ${VOLUME_BASE}/sonarqube_temp:/opt/sonarqube/temp
      - ${VOLUME_BASE}/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: postgres:${POSTGRES_VERSION}
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: ${SONAR_DB_USER}
      POSTGRES_PASSWORD: ${SONAR_DB_PASS}
    volumes:
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ${VOLUME_BASE}/sonar/postgresql/data:/var/lib/postgresql/data
