version: '3.7'
services:
  registry:
    image: registry:2
    container_name: docker-registry
    labels:
      - "PROJECT=registry"
    ports:
      - 5000:5000
    networks:
      - docker-registry-network
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - "/mnt/shopee/backup/registry/images:/var/lib/registry"
      - "/mnt/shopee/backup/registry/config/config.yml:/etc/docker/registry/config.yml"
registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    labels:
      - "PROJECT=registry"
    ports:
      - 3000:80
    networks:
      - docker-registry-network
    environment:
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_HOST=registry
    depends_on:
      - registry
networks:
  docker-registry-network:
    name: docker-registry-network
    labels:
      - "PROJECT=registry"