services:
  gilab:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
    container_name: gitlab
    restart: always
    #hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab_config:/etc/gitlab'
      - gitlab_logs:/var/log/gitlab'
      - gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
  gitlab-runner:
    image: 'gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    restart: unless-stopped
volumes:
  redis-data:
  postgresql-data:
  gitlab_data:
  gitlab_config:
  gitlab_logs:
  gitlab_runner_config:
