version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
    container_name: gitlab
    #platform: linux/x86_64
    restart: unless-stopped
    hostname: 'gitlab.devops.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'http://gitlab.devops.local'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        # nginx['enable'] = false
    ports:
      - '1080:80'
      - '1443:443'
      - '2222:22'
    volumes:
      - ${VOLUME_BASE}/config:/etc/gitlab'
      - ${VOLUME_BASE}/logs:/var/log/gitlab'
      - ${VOLUME_BASE}/data:/var/opt/gitlab'
    networks:
      - gitlab_network
    shm_size: '256m'
  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    container_name: gitlab-runner 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_BASE}/gitlab_runner_config:/etc/gitlab-runner
    restart: unless-stopped
    networks:
      - gitlab_network
    depends_on:
      - gitlab
networks:
  gitlab_network: