version: '3.7'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION}'
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '1080:80'
      - '1443:443'
      - '2224:22'
    volumes:
      - ${VOLUME_BASE}/gitlab/config:/etc/gitlab
      - ${VOLUME_BASE}/gitlab/logs:/var/log/gitlab'
      - ${VOLUME_BASE}/gitlab/data:/var/opt/gitlab'

